force-app/main/default/objects/Basket__c/Basket__c.object-meta.xml
<CustomObject>
    <label>Basket</label>
    <nameField>
        <label>Basket Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Baskets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Basket__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Baskets</relationshipLabel>
    <relationshipName>Baskets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Basket__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Baskets</relationshipLabel>
    <relationshipName>Baskets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/BasketEditorControllerNoMockTest.cls
/*
 * Example of a test class that does not use mocking
 */
@IsTest(IsParallel=true)
public with sharing class BasketEditorControllerNoMockTest {
  @TestSetup
  static void makeData() {
    Account acc = new Account();
    acc.Name = 'Test';
    insert acc;

    Opportunity opp = new Opportunity();
    opp.Name = 'Test Opp';
    opp.StageName = 'Prospecting';
    opp.CloseDate = Date.today().addDays(30);
    opp.AccountId = acc.Id;
    insert opp;

    Basket__c basket = new Basket__c();
    basket.Account__c = acc.Id;
    basket.Opportunity__c = opp.Id;
    insert basket;
  }

  @IsTest
  private static void getBasketRecord() {
    Basket__c basket = [SELECT Id, Name FROM Basket__c LIMIT 1];

    Test.startTest();

    Test.setCurrentPageReference(Page.BasketEditor);
    ApexPages.currentPage().getParameters().put('Id', basket.Id);
    BasketEditorController controller = new BasketEditorController();
    Test.stopTest();

    Assert.areEqual(basket.Id, controller.basket.Id, 'Invalid data');
  }
}